### ISSUE TITLE
Add coverage for puppet environments

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/airgun#106]
* [x] All entities page
![image](https://user-images.githubusercontent.com/10895065/41405448-718326a4-6fd2-11e8-829d-2b789eadb231.png)
* [x] Create/Edit navigation
* [x] Details - Environment
* [x] Details - Locations
* [x] Details - Organizations
* [x] Import(Changed environment) page
![image](https://user-images.githubusercontent.com/10895065/42465742-88b6e5d0-83b5-11e8-8a8c-ab6000c28ac7.png)

**Comment by oshtaier** [comment]
@schlupov pick up that one

**Comment by schlupov** [comment]
@oshtaier  Thank you very much I do appreciate this.

**Comment by schlupov** [comment]
@oshtaier @abalakh  What else should I add for button import? I don't know If I should add some test for import because in ui folder isn't any test for this button. And I have a question for the redirection to Puppet classes, will be enough if I just add button Classes into the view for puppet environments? And also the same question about adding the new test.

**Comment by schlupov** [comment]
@oshtaier  @abalakh  I'm sorry you maybe didn't see my comment here Can you please help me what else to add for this entity?

**Comment by oshtaier** [comment]
I would say, that we need to add support for 'Changed environments' view that will consists of table and update buttons. Just to be able to click on checkbox and push update button. That will require adding one more navigation step into entity (to get on that view you will need to click on import button) and method like update_classes or whatever

**Comment by oshtaier** [comment]
Not needed for GA:
* [ ] Redirection to Puppet classes

**Comment by abalakh** [comment]
Addressed in #160
