### ISSUE TITLE
Failing robottelo test tests/foreman/ui/test_settings.py::test_positive_entries_per_page[entries_per_page]

### ISSUE THREAD

**Issue by dosas** [SatelliteQE/airgun#1161]
The following [test](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_settings.py#L516) is failing:

```
airgun/utils.py", line 73, in get_widget_by_name
        raise AttributeError(
    AttributeError: Object <<class 'airgun.views.task.TasksView'>> has no widget name "Pagination"
```

@mstrlc In your [refactoring](https://github.com/SatelliteQE/airgun/pull/947/files#diff-74f74a32265f2bf134dbfa8c6797f9ed8b4c50904a4abf7fd6e1c32b3d251ff1) you removed the pagination property which is now missing.

**Comment by dosas** [comment]
ping

**Comment by ogajduse** [comment]
@mstrlc does not work in our team anymore. Seeing that @pondrejk is adding pagination back in #1204, it seems that we need to review it more thoroughly.
@omkarkhatavkar is that something we know about? Is it a known issue?

**Comment by omkarkhatavkar** [comment]
This issue was not previously identified, and it is challenging for me to catch such issues as I don't routinely review test case failures.

@mstrlc made commendable efforts to identify areas where PF4 pagination was being used and refactored them as needed. While a single review was conducted by me, unfortunately, this oversight occurred on both my part and @mstrlc's part. Upon revisiting the entire pull request, it became apparent that this was an accidental omission.

Moving forward, it is crucial for PR reviews to be conducted more meticulously, and we should encourage greater participation from **multiple** reviewers. This will help prevent oversights and ensure the overall quality of our codebase.

**Comment by dosas** [comment]
https://github.com/SatelliteQE/airgun/pull/1204
