### ISSUE TITLE
Update airgun according to widgetastic guidelines

### ISSUE THREAD

**Issue by abalakh** [SatelliteQE/airgun#13]
Recently widgetastic guidelines have been introduced:
https://github.com/RedHatQE/widgetastic.core#widgetastic-usage-guidelines

We should take a closer look to them and update all inconsistent places in airgun accordingly.

**Comment by mirzal** [comment]
URL is now https://widgetastic.readthedocs.io/en/latest/guidelines.html

Closing as part of Issues cleanup, since this is not really actionable. We definitely should pay attention to widgetastic guidelines and follow them as closely as we can. We should check for any discrepancies as part of PR reviews, and we should welcome all PRs that align any current code with guidelines.

But I don't see us spending time on reviewing entire framework code, and this is the only way we could correctly close this issue.
