### ISSUE TITLE
Identify all Views that must be added

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/airgun#27]
We need to identify all Views that must be added to support AirGun usage with latest Foreman/Katello upstream.

This will also allow us to clearly identify what tasks are available for future collaborators.

**Comment by oshtaier** [comment]
I think by all we should mean actually 'all' available views. Even if some entities has only tier1 tests, they can be used in other entities in tier3 scope, so we need all of them

**Comment by abalakh** [comment]
Both of you have a point - not all the views are required for t2-t3 automation, but it's pretty hard to determine complete list since entities aren't isolated and entity2 may use entity1 views which were not required for entity1 automation.

But as we won't introduce all the tests at once and will cover entities step by step, i propose to identify the views required for automating one specific entity, then, when we finish - identify for the second etc.
Since we're planning to start with AK tests, I've analyzed all tier2-tier3 UI tests and here's a list of required views for them:

### Activation keys tests:
- [ ] List all AK view
- [ ] Create new AK view
- [ ] AK Details view (Details tab)
- [ ] AK details - host collections - Add tab
- [ ] AK details - host collections - List tab
- [ ] AK details - subscriptions - Add tab
- [ ] AK details - subscriptions - List tab
- [ ] AK details - associations - Content hosts tab
- [ ] AK details - Repository sets tab
- [ ] List all content hosts view
- [ ] Content host details view (Details tab)
- [ ] Content host details - subscriptions - subscriptions tab
- [ ] RedHat Subscriptions - Details tab

**Comment by oshtaier** [comment]
Closing this in favor of https://github.com/SatelliteQE/airgun/issues/120
