### ISSUE TITLE
add a function to select all hosts by checking the select all 

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/airgun#435]
Currently tests that select all created hosts (e.g.  test_positive_bulk_delete_host) select host by selecting them one by one in the table. Checking the select all box in the table will speed things up

**Comment by tstrych** [comment]
+1

**Comment by mirekdlugosz** [comment]
What time difference are we talking about here? In another PR, I saw `test_positive_bulk_delete_host` takes around two minutes to complete, which is on the lower end of scale for UI tests.


It's late, but what seems to make most sense for me right now is to allow `entities_list` parameter to take special string value `ALL`. Then `airgun/entities/host.py::HostsSelectAction::step()` would check if `entities_list` is not a list and has value ALL, and in that case it would select all elements in table. Otherwise, it would iterate over elements and select them individually as it always did.

Assuming you can click "all" in table using Airgun. I don't think we ever do that and widgetastic assigns some special meaning to `Table` header. Without looking at the code, I would assume this might be tricky.
