### ISSUE TITLE
Add BIOS UUID to contenthost view

### ISSUE THREAD

**Issue by swadeley** [SatelliteQE/airgun#462]
The content hosts details page now includes BIOS UUID. This makes test fail [0] when looking for 'OS' calling **ReadOnlyEntry** [1][2].

We need to add entry for BIOS UUID and possible update UUID to Subscription UUID:

        uuid = ReadOnlyEntry(name='Subscription UUID')
        bios_uuid = ReadOnlyEntry(name='BIOS UUID')

then ensure we can match on OS not BIOS in the appropriate place.

[0] https://github.com/SatelliteQE/robottelo/blob/e3f72fb8c3f59934ba773d76c671143b0d3f873a/tests/foreman/ui/test_contenthost.py#L550
[1] https://github.com/SatelliteQE/airgun/blob/6783f57c46a1369fc61bab8c421390d8814aa77d/airgun/views/contenthost.py#L153
[2] https://github.com/SatelliteQE/airgun/blob/6783f57c46a1369fc61bab8c421390d8814aa77d/airgun/widgets.py#L1412

**Comment by mirekdlugosz** [comment]
Looks like `ReadOnlyEntry` does partial match on element content when `name` is provided, so `ReadOnlyEntry(name='OS')` matches `BIOS UUID` instead of `OS`, as it appears first in page structure.

Easy and safe way would be using `locator` instead:
```python
os = ReadOnlyEntry(
    locator=".//dt[., 'OS']/following-sibling::dd[not(contains(@class, 'ng-hide'))][1]"
)
```

Most likely a correct way is removing `contains()` from [`ReadOnlyEntry` `BASE_LOCATOR` definition](https://github.com/SatelliteQE/airgun/blob/master/airgun/widgets.py#L1433), forcing `name` to perform exact match. Since `ReadOnlyEntry` is used all over the place, this will require thorough regression run, to ensure that no test is broken by this change.

Depending on regression run results, we might think about adding new parameter to `ReadOnlyEntry`, so caller can decide if `name` matching should be performed partially (default to retain backwards compatibility) or exactly.

I don't think adding `bios_uuid` definition is really necessary here, but of course it can be done while someone is at it.

**Comment by swadeley** [comment]
> Looks like `ReadOnlyEntry` does partial match on element content when `name` is provided, so `ReadOnlyEntry(name='OS')` matches `BIOS UUID` instead of `OS`, as it appears first in page structure.
> 
> Easy and safe way would be using `locator` instead:
> 
> ```python
> os = ReadOnlyEntry(
>     locator=".//dt[., 'OS']/following-sibling::dd[not(contains(@class, 'ng-hide'))][1]"
> )
> `

Hello @mirekdlugosz 

I found this works:
            os = ReadOnlyEntry(locator=".//dt[.='OS']/following-sibling::dd[not(contains(@class, 'ng-hide'))]")

> 
> Most likely a correct way is removing `contains()` from [`ReadOnlyEntry` `BASE_LOCATOR` definition](https://github.com/SatelliteQE/airgun/blob/master/airgun/widgets.py#L1433), forcing `name` to perform exact match. Since `ReadOnlyEntry` is used all over the place, this will require thorough regression run, to ensure that no test is broken by this change.

Do you mean running all tests that make use of ReadOnlyEntry ?
> 
> Depending on regression run results, we might think about adding new parameter to `ReadOnlyEntry`, so caller can decide if `name` matching should be performed partially (default to retain backwards compatibility) or exactly.
> 
> I don't think adding `bios_uuid` definition is really necessary here, but of course it can be done while someone is at it.

As I am taking the time to fix airgun, I thought I should.


Thank you

**Comment by mirekdlugosz** [comment]
> > Most likely a correct way is removing `contains()` from [`ReadOnlyEntry` `BASE_LOCATOR` definition](https://github.com/SatelliteQE/airgun/blob/master/airgun/widgets.py#L1433), forcing `name` to perform exact match. Since `ReadOnlyEntry` is used all over the place, this will require thorough regression run, to ensure that no test is broken by this change.
> 
> Do you mean running all tests that make use of ReadOnlyEntry ?

I meant: in case you modify `ReadOnlyEntry` class, we need **some** evidence it will not completely break UI automation. I don't think it's reasonable to expect you to run all tests that use that widget (which approximates to all UI tests), but clearly single test for content host would not be enough.

Since you decided to go different way in #463, it kind of doesn't matter now.

> As I am taking the time to fix airgun, I thought I should.

That's an attitude!
