### ISSUE TITLE
pf4.ouia.Button hitting AttributeError in Insights View

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/airgun#581]
We are suppose to use components/widgets from `widgetastic_patternfly4.ouia`.
for example: 
```
from widgetastic_patternfly4.ouia import Button
remediate = Button(component_id='OUIA-Generated-Button-primary-1')
```
But this gives error `{AttributError}'Button' object has no attribute 'args'`. 
Workaround: 

- Removing `__repr__` from  `BaseButton` class of `widgetastic_patternfly4.button`
- Import `Button` class directly from `widgetastic_patternfly4`.

**Comment by jameerpathan111** [comment]
@tpapaioa I faced the issue while using that widget. For example `view.remediate.click()`.
@mshriver can you help describing the issue properly.

**Comment by mshriver** [comment]
This is going to be a bug/issue with wt.pf4 as written, not with airgun.

If you're using a 'regular' button widget in your view where a PF4 button should be used, and airgun issue would cover needing to update it once the pf4 issue has been resolved.

@tpapaioa I haven't looked into this myself yet, but took a look with @jameerpathan111 yesterday, and found that the `__repr__` is causing the AttributeError due to missing `self.args`. This should be set in WidgetDescriptor, I'm not sure what about the OUIA widget pattern is preventing it from getting set. 

https://github.com/RedHatQE/widgetastic.core/blob/master/src/widgetastic/widget/base.py#L117

**Comment by omkarkhatavkar** [comment]
Updating https://github.com/RedHatQE/widgetastic.patternfly4/blob/master/src/widgetastic_patternfly4/button.py#L40 with below code works, will wait to see if there more appropriate solution.   

```python 
    def __repr__(self):
        return "{}({!r})".format(type(self).__name__, self.locator)
```

**Comment by mshriver** [comment]
This was resolved by https://github.com/RedHatQE/widgetastic.patternfly4/pull/119, thanks @omkarkhatavkar
